site_name: SimpleTimerBank
site_url: https://supersheepbear.github.io/SimpleTimerBank
site_description: A simple desktop timer application with a time balance.
site_author: supersheepbear
edit_uri: edit/main/docs/
repo_name: supersheepbear/SimpleTimerBank
copyright: Maintained by <a href="https://supersheepbear.com">supersheepbear</a>.

nav:
  - 'index.md'
  - 'usage.md'
  - 'api_reference.md'
  - 'contributing.md'
  - 'license.md'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/supersheepbear/SimpleTimerBank
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/SimpleTimerBank

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
